[server]
protocol = https
host = 0.0.0.0
port = 8989
daemon = false
log_file = /var/log/report_hub/report_hub.log
log_level = info
pid_file  = /var/run/report_hub.pid
service_dir = /etc/report_hub/service.d
auth_user = steelm
auth_pass = xxx
ssl_key = /etc/ssl/private/report_hub.key
ssl_cert = /etc/ssl/certs/report_hub.pem

[influxdb]
url = http://127.0.0.1:8086
token = xxx
org = madcat
